#pragma once

class Vec2;
class Rect;
class Component;
class Sound;
class Music;
class Sprite;
class State;
class GameObject;
class Face;
class TileSet;
class TileMap;
class Resources;
class InputManager;
class Camera;
class CameraFollower;
class Alien;
class Minion;
class Bullet;